const ActionTypes = {
  BACKGROUND_ERROR: 'BACKGROUND_ERROR',

  GET_TABS_REQUESTED: 'GET_TABS_REQUESTED',
  GET_TABS_FULLFILLED: 'GET_TABS_FULLFILLED',

  OPEN_TABS_REQUESTED: 'OPEN_TABS_REQUESTED',
  OPEN_TABS_FULLFILLED: 'OPEN_TABS_FULLFILLED',

  CLOSE_TABS_REQUESTED: 'CLOSE_TABS_REQUESTED',
  CLOSE_TABS_FULLFILLED: 'CLOSE_TABS_FULLFILLED',

  SWITCH_TAB_REQUESTED: 'SWITCH_TAB_REQUESTED',
  SWITCH_TAB_FULLFILLED: 'SWITCH_TAB_FULLFILLED',

  SWITCH_PROJECT_REQUESTED: 'SWITCH_PROJECT_REQUESTED',
  SWITCH_PROJECT_FULLFILLED: 'SWITCH_PROJECT_FULLFILLED',

  NEW_PROJECT_REQUESTED: 'NEW_PROJECT_REQUESTED',
  NEW_PROJECT_FULLFILLED: 'NEW_PROJECT_FULLFILLED',

  LOAD_PROJECTS_REQUESTED: 'LOAD_PROJECTS_REQUESTED',
  LOAD_PROJECTS_FULLFILLED: 'LOAD_PROJECTS_FULLFILLED',

  ADD_RESOURCE_REQUESTED: 'ADD_RESOURCE_REQUESTED',
  ADD_RESOURCE_FULLFILLED: 'ADD_RESOURCE_FULLFILLED',

  LOAD_RESOURCES_REQUESTED: 'LOAD_RESOURCES_REQUESTED',
  LOAD_RESOURCES_FULLFILLED: 'LOAD_RESOURCES_FULLFILLED',

  DELETE_PROJECT_REQUESTED: 'DELETE_PROJECT_REQUESTED',
  DELETE_PROJECT_FULLFILLED: 'DELETE_PROJECT_FULLFILLED',

  DELETE_RESOUECE_REQUESTED: 'DELETE_RESOURCE_REQUESTED',
  DELETE_RESOUECE_FULLFILLED: 'DELETE_RESOURCE_FULLFILLED',

  SWITCH_VIEW_REQUESTED: 'SWITCH_VIEW_REQUESTED',
  SWITCH_VIEW_FULLFILLED: 'SWITCH_VIEW_FULLFILLED',

  AUTH_USER: 'AUTH_USER',
  DEAUTH_USER: 'DEAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
};

export default ActionTypes;
